// strings.js
const STRINGS = {
  en: {
    // Brand
    brand_sub: 'Inspired by MoeTruyen • Customized by Maditor',

    // Topbar
    model_label: 'Model',
    model_other: 'Other model...',
    provider_label: 'Provider',
    provider_gemini: 'Google Gemini (Direct)',
    provider_9router: '9Router (Local Gateway)',
    provider_custom: 'Custom Proxy',
    base_url_label: 'Base URL',
    base_url_placeholder: 'http://localhost:20128',
    key_label_gemini: 'Gemini API Key',
    key_label_9router: '9Router Key',
    key_label_custom: 'API Key',
    key_placeholder_gemini: 'Enter API key from Google AI Studio',
    key_placeholder_9router: 'Enter 9Router Key (or leave empty if local)',
    key_placeholder_custom: 'Enter API Key',
    open_9router: 'Open 9Router',
    api_key_label: 'Gemini API Key',
    api_key_placeholder: 'Enter API key from Google AI Studio',
    get_key: 'Get key',

    // Lang bar
    source_lang_label: 'Source language',
    target_lang_label: 'Translate to',
    skip_sfx_label: 'Skip SFX (sound effects, onomatopoeia...)',
    add_images: '+ Add images (max 100)',
    ocr_all: 'OCR all',
    translate_all: 'Translate all',
    ocr_translate_all: 'OCR + Translate all',
    clear_all: 'Clear all',
    content_type_webtoon: 'Webtoon',
    content_type_manga: 'Manga',

    // Settings panel
    settings: 'Settings',
    theme_label: 'Theme',
    dark_mode: 'Dark mode',
    light_mode: 'Light mode',
    ui_mode_label: 'UI mode',
    ui_mode_desktop: 'Desktop',
    ui_mode_mobile: 'Mobile',
    replace: 'Replace',
    font_size_label: 'Font size (OCR & Translation)',
    api_usage: 'API usage',
    view_logs: 'View logs',
    error_logs_title: 'Error logs',
    about: 'About',
    shortcut_hint: 'Ctrl+H',

    // Selection bar
    selection_count: '{count} image(s) selected',
    ocr_selected: 'OCR selected',
    translate_selected: 'Translate selected',
    refine_selected: 'Refine selected',
    refine_ocr_selected: 'Refine OCR selected',
    refine_translate_selected: 'Refine Translation selected',
    deselect: 'Deselect',

    // Replace bar
    find_placeholder: 'Find...',
    replace_with_placeholder: 'Replace with...',
    search_in: 'Search in:',
    ocr: 'OCR',
    translation: 'Translation',
    trans_short: 'Trans',
    position_menu: 'Position',
    special_menu: 'Special',
    whole_word: 'Whole word',
    start_with: 'Start with',
    match_case: 'Match case',
    replace_one: 'Replace',
    replace_all: 'Replace all',

    // Manga item
    image_title: 'Image {index}: {name}',
    size_kb: '{size} KB',
    status_idle: 'idle',
    status_processing: 'processing',
    status_completed: 'completed',
    status_error: 'error',
    stop_retry: 'Stop retry',
    edit_mode: 'Edit mode',
    save: 'Save',
    saved: 'Saved',
    save_failed: 'Save failed',
    jump_to_error_image: 'Jump to error image',
    jump_to_error_images: 'Jump to error images ({count})',
    ocr_single: 'OCR',
    translate_single: 'Translate',
    refine: 'Refine',
    refine_ocr: 'Refine OCR',
    refine_translate: 'Refine Translation',
    delete: '', // icon
    ocr_column: 'OCR',
    translation_column: 'Translation',
    copy: 'Copy',
    versions: 'Vers',
    ocr_placeholder: 'OCR not performed',
    translation_placeholder: 'Translation not performed',

    // Summary
    all_ocr: 'All OCR',
    all_translations: 'All translations',
    no_ocr: 'No OCR results yet',
    no_translation: 'No translations yet',
    export: 'Export',
    txt: '.txt',
    docx: '.docx',
    edit_mode_summary: 'Edit mode',
    copy_summary: 'Copy',
    reload: 'Reload',

    // Nav-FAB
    no_images: 'No images yet',
    summary_nav: 'Summary',
    select_all: 'Select all',
    clear_selected: 'Clear',
    // Toast / confirm
    please_wait: 'Please wait',
    enter_api_key_first: 'Enter Gemini API key first.',
    nothing_to_undo: 'Nothing to undo',
    replace_undone: 'Replace undone',
    no_images_to_clear: 'No images to clear',
    no_images_to_ocr: 'No images to OCR',
    no_images_to_translate: 'No images to translate',
    run_ocr_first: 'Run OCR first',
    run_translate_first: 'Run Translate first',
    cannot_delete_now: 'Cannot delete now',
    deleted: 'Deleted',
    ocr_done: 'OCR image {index} done',
    ocr_error: 'OCR error (img {index})',
    translate_done: 'Translation {index} done',
    translate_error: 'Translate error (img {index})',
    refine_ocr_done: 'Refine OCR image {index} done',
    refine_ocr_error: 'Refine OCR error (img {index})',
    refine_translate_done: 'Refine translation image {index} done',
    refine_translate_error: 'Refine translation error (img {index})',
    stop_queue_confirm: 'Stop queue? Current image finishes, rest cancelled.',
    stopping: 'Stopping...',
    stopped: 'Stopped ({done}/{total})',
    batch_done: '{kind} done ({done})',
    combined_done: 'OCR+Translate done ({done})',
    cannot_clear_now: 'Cannot clear now',
    cleared_all: 'Cleared all',
    no_images_selected: 'No images selected',
    clear_selected_confirm: 'Clear selected image(s)?',
    cleared_count: 'Cleared {count} image(s)',
    refine_ocr_confirm: 'Re-scan bubble boundaries to fix split/merged OCR lines\nFor {count} selected image(s).',
    refine_translate_confirm: 'Refine translation\nFor {count} selected image(s).',
    translate_confirm: 'Translating from "{source}" to "{target}".\nTranslate {count} selected image(s)?',
    ocr_confirm: 'OCR source is "{source}".\nRun OCR for {count} selected image(s)?',
    no_content: 'No content',
    exported: 'Exported .{format}',
    export_failed: 'Export failed',
    copied: 'Copied',
    copy_failed: 'Copy failed',
    reset_usage_confirm: 'Reset usage counter?',
    usage_reset: 'Usage reset',
    clear_logs_confirm: 'Clear error logs?',
    logs_cleared: 'Logs cleared',
    no_errors: 'No errors logged yet.',
    no_versions: 'No versions saved yet',
    applied_version: 'Applied version #{n}',
    saved_edit: 'Saved (Ctrl+S)',
    no_translations_to_refine: 'No translations to refine',
    images_only: 'Images only',
    skipped_duplicates: 'Skipped {count} duplicate(s)',
    max_images: 'Max {max} images',
    preparing: 'Preparing {count}...',
    added_images: 'Added {count} images',
    restored_images: 'Restored {count} image(s)',
    unmatched_cache: '{count} unmatched',
    edit_mode_on: 'Edit mode on',
    reloaded: 'Reloaded',
    rate_limited: 'Rate limited ({seconds}s)',
    model_busy_retry: 'Model overloaded, retrying in {seconds}s ({attempt}/{max})',
    model_busy_switch: 'Model "{model}" is overloaded. Queue stopped, pick another model and run again.',
    model_busy_ask_auto: 'Model "{model}" is still overloaded. Turn on auto-switch model and continue?',
    model_switched: 'Switched to {model}',
    all_models_busy: 'All models are overloaded. Queue stopped, please try again later.',
    auto_switch_model_label: 'Auto-switch model when overloaded',
    retry_stopped: 'Retry stopped',
    cannot_extract: 'Could not extract text from image.',
    translation_empty: 'Translation is empty, please try again.',
    no_ocr_to_refine: 'No existing OCR result to refine.',
    no_translation_to_refine: 'No existing translation result to refine.',
    missing_api_key: 'Missing API key',
    refine_ocr_empty: 'Refine OCR returned empty result.',
    refine_translate_empty: 'Refine translation returned empty result.',
    error_prefix: 'Error',
    could_not_read_file: 'Could not read file',
    // Extra keys (toast / confirm bo sung)
    cache_ready: 'Cache ready ({count})',
    saving: 'Saving...',
    replaced_count: 'Replaced {count} occurrence(s)',
    no_matches_found: 'No matches found',
    open_failed: 'Open failed',
    rate_limit_stop_confirm: 'API is busy / rate limited. Stop retry queue?',
    saved_image: 'Saved (image {index})',
    delete_confirm: 'Delete "{name}"?',
    ocr_source_confirm: 'OCR source: {source}.',
    translate_source_target_confirm: 'Translate {source} \u2192 {target}.',
    ocr_translate_confirm: 'OCR {source}\nTranslate {target}.',
    delete_all_confirm: 'Delete ALL images?',
    close_confirm: 'Close VisionBox? Unsaved changes may be lost.',
    continue_btn: 'Continue',
    cancel_btn: 'Cancel',
    ok_btn: 'OK',
    yes_btn: 'Yes',
    no_btn: 'No',
    skipped_note: ', skipped {count}',
    adjust_image_size: 'Adjust image size',
    image_size: 'Image size',
    resize_preview: 'Resize image preview',
    reset_original_size: 'Reset to original size',
    stop_retry_title: 'Retrying after a rate limit (429) or overloaded model (503). Click to stop the queue.',
    refine_tooltip: 'Refine OCR or Translation',
    refine_ocr_tooltip: 'Re-scan bubble boundaries to fix split/merged lines',
    refine_translate_tooltip: 'Refine translation with an optional custom instruction',
    select_this_image: 'Select this image',
    delete_this_image: 'Delete this image',
    drag_to_resize: 'Drag to resize',
    view_versions_title: 'View versions',
    versions_title: '{kind} Versions (Image {index})',
    nav_image_label: 'Image {index}',
    images_selected_suffix: 'image(s) selected',
    dropzone_placeholder: 'Drag and drop images here, or click "+ Add images" to start.',

    // Language names (dropdowns + confirm messages)
    lang_ko: 'Korean (한국어)',
    lang_en: 'English',
    lang_zh: 'Chinese (中文)',
    lang_vi: 'Vietnamese',
    lang_ja: 'Japanese',
    lang_manga_ja: 'Manga Japanese',
    lang_manga_en: 'Manga English',
    prompt_placeholder: 'Prompt...',

    // Usage modal
    usage_total_calls: 'Total calls',
    usage_success: 'Success',
    usage_failed: 'Failed',
    usage_note: 'Tracks requests in the current session only — resets when the tool closes (no cross-session saving).',
    reset_counter: 'Reset counter',

    // Logs modal
    clear_logs_btn: 'Clear logs',

    // About / Shortcuts modal
    shortcuts_title: 'Keyboard Shortcuts',
    close_title: 'Close',
    shortcut_open_file: 'Open file picker',
    shortcut_ocr_all: 'OCR all',
    shortcut_translate_all: 'Translate all',
    shortcut_refine_translate_all: 'Refine Translation all',
    shortcut_select_all_images: 'Select all images',
    shortcut_deselect_all: 'Deselect all',
    shortcut_clear_all_images: 'Clear all images',
    shortcut_open_replace: 'Open Replace bar',
    shortcut_save_edit_mode: 'Save edit mode',
    shortcut_confirm_dialog: 'Confirm dialog',
    shortcut_cancel_dialog: 'Cancel dialog',
    // ... có thể thêm các key khác nếu cần
  },
  vi: {
    // Brand
    brand_sub: 'Ý tưởng từ Moè Truyện • Phát triển bởi Maditor',

    // Topbar
    model_label: 'Mô hình',
    model_other: 'Mô hình khác...',
    provider_label: 'Nhà cung cấp',
    provider_gemini: 'Google Gemini (Trực tiếp)',
    provider_9router: '9Router (Cổng cục bộ)',
    provider_custom: 'Proxy tùy chỉnh',
    base_url_label: 'Base URL',
    base_url_placeholder: 'http://localhost:20128',
    key_label_gemini: 'API Key Gemini',
    key_label_9router: 'Key 9Router',
    key_label_custom: 'API Key',
    key_placeholder_gemini: 'Nhập API Key từ Google AI Studio',
    key_placeholder_9router: 'Nhập Key 9Router (để trống nếu chạy local)',
    key_placeholder_custom: 'Nhập API Key',
    open_9router: 'Mở 9Router',
    api_key_label: 'API Key Gemini',
    api_key_placeholder: 'Nhập API Key từ Google AI Studio',
    get_key: 'Lấy Mã',

    // Lang bar
    source_lang_label: 'Ngôn ngữ nguồn',
    target_lang_label: 'Dịch sang',
    skip_sfx_label: 'Bỏ qua SFX (hiệu ứng âm thanh, tượng thanh...)',
    add_images: '+ Thêm ảnh (tối đa 100)',
    ocr_all: 'Quét tất cả',
    translate_all: 'Dịch tất cả',
    ocr_translate_all: 'Quét + Dịch tất cả',
    clear_all: 'Xóa tất cả',
    content_type_webtoon: 'Webtoon',
    content_type_manga: 'Manga',

    // Settings panel
    settings: 'Cài đặt',
    theme_label: 'Giao diện',
    dark_mode: 'Tối',
    light_mode: 'Sáng',
    ui_mode_label: 'Giao diện',
    ui_mode_desktop: 'Máy tính',
    ui_mode_mobile: 'Điện thoại',
    replace: 'Tìm/thay thế',
    font_size_label: 'Cỡ chữ (Quét & Dịch)',
    api_usage: 'Lượt Dùng API',
    view_logs: 'Xem Lỗi',
    error_logs_title: 'Nhật ký lỗi',
    about: 'Giới thiệu',
    shortcut_hint: 'Ctrl+H',

    // Selection bar
    selection_count: 'Đã chọn {count} ảnh',
    ocr_selected: 'Quét ảnh đã chọn',
    translate_selected: 'Dịch ảnh đã chọn',
    refine_selected: 'Tinh chỉnh ảnh đã chọn',
    refine_ocr_selected: 'Tinh chỉnh OCR',
    refine_translate_selected: 'Tinh chỉnh bản dịch',
    deselect: 'Bỏ chọn',

    // Replace bar
    find_placeholder: 'Tìm...',
    replace_with_placeholder: 'Thay bằng...',
    search_in: 'Tìm trong:',
    ocr: 'Quét',
    translation: 'Dịch',
    trans_short: 'Dịch',
    position_menu: 'Vị trí',
    special_menu: 'Đặc biệt',
    whole_word: 'Toàn bộ từ',
    start_with: 'Bắt đầu bằng',
    match_case: 'Phân biệt hoa/thường',
    replace_one: 'Thay thế',
    replace_all: 'Thay thế tất cả',

    // Manga item
    image_title: 'Ảnh {index}: {name}',
    size_kb: '{size} KB',
    status_idle: 'chờ',
    status_processing: 'đang xử lý',
    status_completed: 'hoàn thành',
    status_error: 'lỗi',
    stop_retry: 'Dừng thử lại',
    edit_mode: 'Sửa',
    save: 'Lưu',
    saved: 'Đã lưu',
    save_failed: 'Lưu thất bại',
    jump_to_error_image: 'Đi đến ảnh bị lỗi',
    jump_to_error_images: 'Đi đến các ảnh bị lỗi ({count})',
    ocr_single: 'Quét',
    translate_single: 'Dịch',
    refine: 'Tinh chỉnh',
    refine_ocr: 'Tinh chỉnh Quét',
    refine_translate: 'Tinh chỉnh Dịch',
    delete: '',
    ocr_column: 'Bản Quét',
    translation_column: 'Bản Dịch',
    copy: 'Sao chép',
    versions: 'Lịch sử',
    ocr_placeholder: 'Chưa thực hiện Quét',
    translation_placeholder: 'Chưa thực hiện Dịch',

    // Summary
    all_ocr: 'Tất cả bản Quét',
    all_translations: 'Tất cả bản Dịch',
    no_ocr: 'Chưa có kết quả Quét',
    no_translation: 'Chưa có bản Dịch',
    export: 'Xuất',
    txt: '.txt',
    docx: '.docx',
    edit_mode_summary: 'Sửa',
    copy_summary: 'Sao chép',
    reload: 'Tải lại',

    // Nav-FAB
    no_images: 'Chưa có ảnh',
    summary_nav: 'Tổng Hợp',
    select_all: 'Chọn tất cả',
    clear_selected: 'Xóa',
    // Toast / confirm
    please_wait: 'Vui lòng chờ',
    enter_api_key_first: 'Nhập API Key Gemini trước.',
    nothing_to_undo: 'Không có gì để hoàn tác',
    replace_undone: 'Hoàn tác thay thế thành công',
    no_images_to_clear: 'Không có ảnh để xóa',
    no_images_to_ocr: 'Không có ảnh để Quét',
    no_images_to_translate: 'Không có ảnh để Dịch',
    run_ocr_first: 'Chạy Quét trước',
    run_translate_first: 'Chạy Dịch trước',
    cannot_delete_now: 'Không thể xóa ngay bây giờ',
    deleted: 'Đã xóa',
    ocr_done: 'Quét ảnh {index} hoàn tất',
    ocr_error: 'Lỗi Quét (ảnh {index})',
    translate_done: 'Dịch ảnh {index} hoàn tất',
    translate_error: 'Lỗi dịch (ảnh {index})',
    refine_ocr_done: 'Tinh chỉnh Quét ảnh {index} hoàn tất',
    refine_ocr_error: 'Lỗi tinh chỉnh Quét (ảnh {index})',
    refine_translate_done: 'Tinh chỉnh Dịch ảnh {index} hoàn tất',
    refine_translate_error: 'Lỗi tinh chỉnh Dịch (ảnh {index})',
    stop_queue_confirm: 'Dừng hàng đợi? Ảnh hiện tại sẽ hoàn thành, các ảnh còn lại bị hủy.',
    stopping: 'Đang dừng...',
    stopped: 'Đã dừng ({done}/{total})',
    batch_done: '{kind} hoàn tất ({done})',
    combined_done: 'Quét và Dịch hoàn tất ({done})',
    cannot_clear_now: 'Không thể xóa khi đang xử lý',
    cleared_all: 'Đã xóa tất cả',
    no_images_selected: 'Chưa chọn ảnh',
    clear_selected_confirm: 'Xóa ảnh đã chọn?',
    cleared_count: 'Đã xóa {count} ảnh',
    refine_ocr_confirm: 'Quét lại ranh giới bong bóng để sửa lỗi tách/gộp dòng Quét\nCho {count} ảnh đã chọn.',
    refine_translate_confirm: 'Tinh chỉnh bản Dịch\nCho {count} ảnh đã chọn.',
    translate_confirm: 'Dịch từ "{source}" sang "{target}".\nDịch {count} ảnh đã chọn?',
    ocr_confirm: 'Ngôn ngữ nguồn là "{source}".\nChạy Quét cho {count} ảnh đã chọn?',
    no_content: 'Không có nội dung',
    exported: 'Xuất .{format} thành công',
    export_failed: 'Xuất thất bại',
    copied: 'Đã sao chép',
    copy_failed: 'Sao chép thất bại',
    reset_usage_confirm: 'Đặt lại bộ đếm sử dụng?',
    usage_reset: 'Đã đặt lại bộ đếm',
    clear_logs_confirm: 'Xóa nhật ký lỗi?',
    logs_cleared: 'Đã xóa nhật ký',
    no_errors: 'Chưa có lỗi nào được ghi lại.',
    no_versions: 'Chưa có phiên bản nào được lưu',
    applied_version: 'Đã áp dụng phiên bản #{n}',
    saved_edit: 'Đã lưu (Ctrl+S)',
    no_translations_to_refine: 'Không có bản dịch nào để tinh chỉnh',
    images_only: 'Chỉ chấp nhận ảnh',
    skipped_duplicates: 'Bỏ qua {count} ảnh trùng',
    max_images: 'Tối đa {max} ảnh',
    preparing: 'Đang chuẩn bị {count}...',
    added_images: 'Đã thêm {count} ảnh',
    restored_images: 'Đã khôi phục {count} ảnh',
    unmatched_cache: '{count} ảnh không khớp bộ nhớ đệm',
    edit_mode_on: 'Vào chế độ chỉnh sửa.',
    reloaded: 'Đã tải lại',
    rate_limited: 'Giới hạn tốc độ ({seconds}s)',
    model_busy_retry: 'Mô hình quá tải, thử lại sau {seconds}s ({attempt}/{max})',
    model_busy_switch: 'Mô hình "{model}" đang quá tải. Đã dừng hàng chờ, hãy đổi mô hình khác rồi chạy lại.',
    model_busy_ask_auto: 'Mô hình "{model}" vẫn quá tải. Bật tự đổi mô hình và tiếp tục?',
    model_switched: 'Đã chuyển sang {model}',
    all_models_busy: 'Tất cả mô hình đều đang quá tải. Đã dừng hàng chờ, hãy thử lại sau.',
    auto_switch_model_label: 'Tự đổi mô hình khi quá tải',
    retry_stopped: 'Đã dừng thử lại',
    cannot_extract: 'Không thể trích xuất văn bản từ ảnh.',
    translation_empty: 'Bản dịch trống, vui lòng thử lại.',
    no_ocr_to_refine: 'Chưa có kết quả Quét để tinh chỉnh.',
    no_translation_to_refine: 'Chưa có bản Dịch để tinh chỉnh.',
    missing_api_key: 'Thiếu API key',
    refine_ocr_empty: 'Tinh chỉnh Quét trả về kết quả trống.',
    refine_translate_empty: 'Tinh chỉnh Dịch trả về kết quả trống.',
    error_prefix: 'Lỗi',
    could_not_read_file: 'Không thể đọc file',
    // Extra keys (toast / confirm bổ sung)
    cache_ready: 'Bộ nhớ đệm sẵn sàng ({count})',
    saving: 'Đang lưu...',
    replaced_count: 'Đã thay thế {count} chỗ',
    no_matches_found: 'Không tìm thấy kết quả',
    open_failed: 'Mở thất bại',
    rate_limit_stop_confirm: 'API đang bận / bị giới hạn. Dừng hàng đợi thử lại?',
    saved_image: 'Đã lưu (ảnh {index})',
    delete_confirm: 'Xóa "{name}"?',
    ocr_source_confirm: 'Ngôn ngữ nguồn Quét: {source}.',
    translate_source_target_confirm: 'Dịch {source} \u2192 {target}.',
    ocr_translate_confirm: 'Quét {source} và Dịch sang {target}.',
    delete_all_confirm: 'Xóa TẤT CẢ ảnh?',
    close_confirm: 'Đóng VisionBox? Các thay đổi chưa lưu có thể bị mất.',
    continue_btn: 'Tiếp tục',
    cancel_btn: 'Hủy',
    ok_btn: 'OK',
    yes_btn: 'Có',
    no_btn: 'Không',
    skipped_note: ', bỏ qua {count}',
    adjust_image_size: 'Điều chỉnh kích thước ảnh',
    image_size: 'Kích thước ảnh',
    resize_preview: 'Kéo để đổi kích thước xem trước',
    reset_original_size: 'Đặt lại kích thước gốc',
    stop_retry_title: 'Đang thử lại do bị giới hạn (429) hoặc mô hình quá tải (503). Nhấn để dừng hàng đợi.',
    refine_tooltip: 'Tinh chỉnh Quét hoặc Dịch',
    refine_ocr_tooltip: 'Quét lại ranh giới bong bóng để sửa lỗi tách/gộp dòng',
    refine_translate_tooltip: 'Tinh chỉnh bản dịch với hướng dẫn tùy chọn',
    select_this_image: 'Chọn ảnh này',
    delete_this_image: 'Xóa ảnh này',
    drag_to_resize: 'Kéo để đổi kích thước',
    view_versions_title: 'Xem lịch sử phiên bản',
    versions_title: 'Phiên bản {kind} (Ảnh {index})',
    nav_image_label: 'Ảnh {index}',
    images_selected_suffix: 'ảnh đã chọn',
    dropzone_placeholder: 'Kéo thả ảnh vào đây, hoặc nhấn "+ Thêm ảnh" để bắt đầu.',

    // Language names (dropdowns + confirm messages)
    lang_ko: 'Tiếng Hàn',
    lang_en: 'Tiếng Anh',
    lang_zh: 'Tiếng Trung',
    lang_vi: 'Tiếng Việt',
    lang_ja: 'Tiếng Nhật',
    lang_manga_ja: 'Manga tiếng Nhật',
    lang_manga_en: 'Manga tiếng Anh',
    prompt_placeholder: 'Nhập yêu cầu...',

    // Usage modal
    usage_total_calls: 'Tổng lượt gọi',
    usage_success: 'Thành công',
    usage_failed: 'Thất bại',
    usage_note: 'Chỉ đếm request trong phiên hiện tại — sẽ reset khi đóng tool (không lưu qua phiên khác).',
    reset_counter: 'Đặt lại bộ đếm',

    // Logs modal
    clear_logs_btn: 'Xóa nhật ký',

    // About / Shortcuts modal
    shortcuts_title: 'Phím tắt',
    close_title: 'Đóng',
    shortcut_open_file: 'Mở hộp thoại chọn file',
    shortcut_ocr_all: 'Quét tất cả',
    shortcut_translate_all: 'Dịch tất cả',
    shortcut_refine_translate_all: 'Tinh chỉnh Dịch tất cả',
    shortcut_select_all_images: 'Chọn tất cả ảnh',
    shortcut_deselect_all: 'Bỏ chọn tất cả',
    shortcut_clear_all_images: 'Xóa tất cả ảnh',
    shortcut_open_replace: 'Mở thanh Tìm/Thay thế',
    shortcut_save_edit_mode: 'Lưu chế độ chỉnh sửa',
    shortcut_confirm_dialog: 'Xác nhận hộp thoại',
    shortcut_cancel_dialog: 'Hủy hộp thoại',
  }
};